---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

cnvpytor:
  container: "docker://kristinebilgrav/cnvpytor"

config_manta_t:
  container: "docker://hydragenetics/manta:1.6.0"
  extra: "--exome --callRegions /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz"

expansionhunter:
  container: "docker://hydragenetics/expansionhunter:5.0.0"
  variant_catalog: ""

exomedepth:
  bedfile: ""
  conifer: ""
  container: ""
  ED_common: ""
  reference_count: ""
  WW25: ""

manta_run_workflow_n:
  container: "docker://hydragenetics/manta:1.6.0"

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

tiddit:
  container: "shub://J35P312/TIDDIT:latest"
