---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.8"

automap:
  container: "docker://hydragenetics/automap:1.2"
  build: "hg38"
  extra: "--DP 10 --minsize 3 --chrX"

cnvkit_export_seg:
  extra: "--enumerate-chroms"

cnvpytor_readdepth:
  container: "docker://hydragenetics/cnvpytor:1.2.1"
  length_list: ""

cnvpytor_filter:
  container: "docker://hydragenetics/cnvpytor:1.2.1"
  calling_model: "rd_mean_shift"
  dG_range: ""
  p_range: ""
  pN_range: ""
  Q0_range: ""
  view: ""

expansionhunter:
    container: "docker://hydragenetics/expansionhunter:5.0.0"

exomedepth:
  bedfile: ""
  conifer: ""
  container: ""
  ED_common: ""
  reference_count: ""
  WW25: ""

manta_config_n:
  container: "docker://hydragenetics/manta:1.6.0"
  extra: ""

manta_run_workflow_n:
  container: "docker://hydragenetics/manta:1.6.0"

pbsv_discover:
  container: "docker://hydragenetics/pbsv:2.9.0"

pbsv_call:
  container: "docker://hydragenetics/pbsv:2.9.0"
  ccs: "--ccs"

pbsv_index:
  extra: "-c '#' -s 3 -b 4 -e 4 "

pindel_update_vcf:
  container: "docker://hydragenetics/picard:2.25.4"

smn_caller:
  container: "docker://hydragenetics/smncopynumbercaller:1.1.2"
  genome_version: ""

smn_charts:
  container: "docker://hydragenetics/smncopynumbercaller:1.1.2"

 sniffles:
   container: "docker://hydragenetics/sniffles2:2.0.7"
   extra: "" 
   non_germline: "" #set to  --non-germline if running somatic
   
tiddit:
  container: "docker://hydragenetics/tiddit:3.3.2"

upd:
  container: "docker://hydragenetics/upd:0.1.1"
  extra: "--vep "
