---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

cnvpytor:
  container: "docker://kristinebilgrav/cnvpytor"

expansionhunter:
  container: "docker://hydragenetics/expansionhunter:5.0.0"
  variant_catalog: ""

exomedepth:
  bedfile: ""
  conifer: ""
  container: ""
  ED_common: ""
  reference_count: ""
  WW25: ""

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

tiddit:
  container: "shub://J35P312/TIDDIT:latest"
