---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

cnvpytor:
  container: "docker://kristinebilgrav/cnvpytor"

expansionhunter:
  container: "docker://hydragenetics/expansionhunter:5.0.0"
  variant_catalog: ""/beegfs-storage/projects/wp4/nobackup/WGS_utveckling/expansionhunter/padraic_testing/RepeatCatalogs-1.0.0/hg38/variant_catalog.json"

exomedepth:
  bedfile: ""
  conifer: ""
  container: ""
  ED_common: ""
  reference_count: ""
  WW25: ""

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

tiddit:
  container: "docker://jemten/tiddit"
