resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.8"

reference:
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  design_intervals_gatk_cnv: "reference/twist_DNA_solid.HES45.annotated.interval_list"
  fasta: "reference/HES45.fna"

cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  method: "hybrid"
  normal_reference: "reference/cnvkit_Twist_PoN_chr1.cnn"

cnvkit_call:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_diagram:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_scatter:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_vcf:
  container: "docker://hydragenetics/cnvkit:0.9.9"

exomedepth_call:
  bedfile: "reference/twist_DNA_solid.chr1.exomedepth.annotated.bed"
  container: "docker://hydragenetics/exomedepth:1.1.15"
  ref_count: "reference/ref_count.txt"

gatk_collect_read_counts:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_denoise_read_counts:
  container: "docker://hydragenetics/gatk4:4.2.2.0"
  normal_reference: "reference/twist_DNA_solid.HES45.GATK_cnv.PoN.hdf5"

gatk_collect_allelic_counts:
  container: "docker://hydragenetics/gatk4:4.2.2.0"
  SNP_interval: "reference/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_model_segments:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_call_copy_ratio_segments:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

gatk_seq_to_vcf:
  container: "docker://hydragenetics/gatk4:4.2.2.0"

pindel_generate_config:
  container: "docker://hydragenetics/common:0.1.0"

manta_config_t:
  container: "docker://hydragenetics/manta:1.6.0"

manta_config_tn:
  container: "docker://hydragenetics/manta:1.6.0"

manta_run_workflow_t:
  container: "docker://hydragenetics/manta:1.6.0"

manta_run_workflow_tn:
  container: "docker://hydragenetics/manta:1.6.0"

pindel_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

pindel_call:
  bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  container: "docker://hydragenetics/pindel:0.2.5b9"

pindel2vcf:
  container: "docker://hydragenetics/pindel:0.2.5b9"

svdb_merge:
  cnv_callers:
    - "cnvkit"
    - "gatk"
    - "pindel"
  container: "docker://hydragenetics/svdb:2.6.0"

svdb_query:
  container: "docker://hydragenetics/svdb:2.6.0"
  db_string: "--db reference/normal_26_svdb_0.8.vcf"
