resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.0"

reference:
  fasta: "reference/HES45.fna"
  design_bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"
  design_intervals_gatk_cnv: "reference/twist_DNA_solid.HES45.annotated.interval_list"

cnvkit_batch:
  container: "docker://marrip/cnvkit:0.9.9"
  method: "hybrid"
  normal_reference: "reference/cnvkit_Twist_PoN_chr1.cnn"

cnvkit_call:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_diagram:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_scatter:
  container: "docker://marrip/cnvkit:0.9.9"

cnvkit_scatter_regions:
  container: "docker://marrip/cnvkit:0.9.9"
  region_file: "reference/cnvkit_scatter_regions.txt"

cnvkit_vcf:
  container: "docker://hydragenetics/common:0.1.0"

config_manta_t:
  container: "docker://marrip/manta:v1.6.0"

config_manta_tn:
  container: "docker://marrip/manta:v1.6.0"

exomedepth:
  bedfile: "reference/twist_DNA_solid.chr1.exomedepth.annotated.bed"
  ref_count: "reference/ref_count.txt"
  container: "docker://hydragenetics/exomedepth:1.1.15"

gatk_cnv_collect_read_counts:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_denoise_read_counts:
  container: "docker://gmsuppsala/somatic:develop"
  normal_reference: "reference/twist_DNA_solid.HES45.GATK_cnv.PoN.hdf5"

gatk_cnv_collect_allelic_counts:
  container: "docker://gmsuppsala/somatic:develop"
  SNP_interval: "reference/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_model_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://gmsuppsala/somatic:develop"

gatk_cnv_vcf:
  container: "docker://hydragenetics/common:0.1.0"

generate_pindel_config:
  container: "docker://hydragenetics/common:0.1.0"

manta_run_workflow_t:
  container: "docker://marrip/manta:v1.6.0"

manta_run_workflow_tn:
  container: "docker://marrip/manta:v1.6.0"

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

pindel_call:
  container: "docker://hydragenetics/pindel:0.2.5b9"
  bedfile: "reference/twist_DNA_solid.chr1.annotated.bed"

pindel2vcf:
  container: "docker://hydragenetics/pindel:0.2.5b9"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.6.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"

svdb_query:
  container: "docker://hydragenetics/svdb:2.6.0"
  db_string: "--db reference/normal_26_svdb_0.8.vcf"
